# Generated by Django 5.0.2 on 2024-03-05 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_urls',
            new_name='image_url',
        ),
    ]
